version: '3.1'

services:

  redmine:
    image: redmine:5.1.3
    restart: always
    ports:
      - "8010:3000"
      - "80:3000"
    environment:
      REDMINE_DB_MYSQL: ${REDMINE_DB_MYSQL}
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
      REDMINE_SECRET_KEY_BASE: ${REDMINE_SECRET_KEY_BASE}
    volumes:
      - ./redmine/config:/usr/src/redmine/config
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/log:/usr/src/redmine/log

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  db_backup:
    image: mysql:8.0
    restart: always
    volumes:
      - ./db_backups:/backups
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: /bin/sh -c "while true; do mysqldump -h db -u root -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} > /backups/redmine_backup_$(date +%F_%H-%M-%S).sql; sleep 86400; done"
    depends_on:
      - db

  db_restore:
    image: mysql:8.0
    volumes:
      - ./db_backups:/backups
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    entrypoint:
      - /bin/sh
      - -c
      - |
        if [ -z "$BACKUP_FILE" ]; then
          echo "ERROR: BACKUP_FILE is not set";
          exit 1;
        fi;
        if [ ! -f "/backups/$BACKUP_FILE" ]; then
          echo "ERROR: Backup file not found";
          exit 1;
        fi;
        mysql -h db -u root -p${MYSQL_ROOT_PASSWORD} ${MYSQL_DATABASE} < /backups/$BACKUP_FILE
    depends_on:
      - db
